### ISSUE TITLE
fxml 文件为什么为打不开

### ISSUE THREAD

**Issue by chefqing** [greyovo/OnlyViewer#1]
java.io.IOException: javafx.fxml.LoadException: 
/C:/Users/user/Desktop/OnlyViewer-master/OnlyViewer-master/src/onlyviewer/home/resources/fxml/FileTreeView.fxml

	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:92)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:80)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:95)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2370)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:655)
	at com.oracle.javafx.scenebuilder.app.DocumentWindowController.loadFromFile(DocumentWindowController.java:386)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.performOpenFiles(SceneBuilderApp.java:579)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleOpenFilesAction(SceneBuilderApp.java:447)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.handleLaunch(SceneBuilderApp.java:427)
	at com.oracle.javafx.scenebuilder.app.AppPlatform.requestStartGeneric(AppPlatform.java:139)
	at com.oracle.javafx.scenebuilder.app.AppPlatform.requestStart(AppPlatform.java:106)
	at com.oracle.javafx.scenebuilder.app.SceneBuilderApp.start(SceneBuilderApp.java:371)
	at com.sun.javafx.application.LauncherImpl$8.run(LauncherImpl.java:837)
	at com.sun.javafx.application.PlatformImpl$7.run(PlatformImpl.java:335)
	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.access$300(WinApplication.java:39)
	at com.sun.glass.ui.win.WinApplication$4$1.run(WinApplication.java:112)
	at java.lang.Thread.run(Thread.java:744)
Caused by: javafx.fxml.LoadException: 
/C:/Users/user/Desktop/OnlyViewer-master/OnlyViewer-master/src/onlyviewer/home/resources/fxml/FileTreeView.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2617)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2864)
	at javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2708)
	at javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2677)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2517)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:89)
	... 22 more
Caused by: java.lang.ClassNotFoundException: com.jfoenix.controls.JFXTreeView
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2932)
	at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2921)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2862)
	... 27 more

**Comment by greyovo** [comment]
Maven 拉取 jfoenix 依赖了吗

```shell
mvn install
```

**Comment by chefqing** [comment]
拉了

**Comment by greyovo** [comment]
那很奇怪，根据你的报错提示 `ClassNotFoundException` 我也没办法了

**Comment by chefqing** [comment]
好的，谢谢

**Comment by sabahmax-dev** [comment]
Hi！我看到 FXML 打不开是因为 `ClassNotFoundException: com.jfoenix.controls.JFXTreeView`，也就是 FXML 里引用的 JFXTreeView 类在运行时找不到。

我已经开了 PR：https://github.com/greyovo/OnlyViewer/pull/2 ，修复了缺少/未正确引入 JFoenix 依赖导致 `FileTreeView.fxml` 加载失败的问题，合并后应该可以正常打开 FXML 了。麻烦帮忙 review 一下，谢谢！
